server:
   port: 8073
spring:
   application:
       name: helloweb
eureka:
   client:
       serviceUrl:
           defaultZone: http://localhost:8761/eureka

#   servlet:   
#      context-path: /helloweb/
